# Sistemas de Ecuaciones Lineales Especiales

In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

## Sustitución hacia adelante

In [3]:
def forsub(L, bs):
    """
    n: size de x
    """
    n = bs.size
    xs = np.zeros(n)
    for i in range(n):
        # i recorre desde 0 hasta n-1
        xs[i] = (bs[i] - L[i, :i] @ xs[:i]) / L[i, i]
    return xs

In [4]:
help(np.tril)

Help on _ArrayFunctionDispatcher in module numpy:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    For arrays with ``ndim`` exceeding 2, `tril` will apply to the final two
    axes.
    
    Parameters
    ----------
    m : array_like, shape (..., M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (..., M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])
    
    >>> np.tril(np.arange(3*4*5).reshape(3, 4, 5))
    array([[[ 

In [5]:
L = np.array([[1, 3, 8], [-2, np.pi, 0], [2, -1, 1]])

In [6]:
L

array([[ 1.        ,  3.        ,  8.        ],
       [-2.        ,  3.14159265,  0.        ],
       [ 2.        , -1.        ,  1.        ]])

In [7]:
L = np.tril(L)

In [8]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [-2.        ,  3.14159265,  0.        ],
       [ 2.        , -1.        ,  1.        ]])

In [9]:
i = 2
L[i, :i]  # desde 0 hasta i - 1

array([ 2., -1.])

In [10]:
b = np.array([1, 2, 3])

In [11]:
b

array([1, 2, 3])

In [12]:
b[:2]

array([1, 2])

In [13]:
x = np.zeros(3)

In [14]:
i = 1
x[i] = (b[i] - L[i, :i] @ x[:i]) / L[i, i]

In [15]:
L[i, :i]

array([-2.])

In [16]:
x[:1]

array([0.])

In [17]:
x

array([0.        , 0.63661977, 0.        ])

In [18]:
for i in range(0, 3):
    print(L[i, i])

1.0
3.141592653589793
1.0


In [19]:
B = np.tril(np.random.rand(3, 3))

In [20]:
B

array([[0.97186357, 0.        , 0.        ],
       [0.51832   , 0.8011707 , 0.        ],
       [0.6552698 , 0.74590637, 0.72895521]])

## Sustitución hacia atrás

In [21]:
def backsub(U, bs):
    n = bs.size
    xs = np.zeros(n)
    for i in reversed(range(n)):
        xs[i] = (bs[i] - U[i, i + 1 :] @ xs[i + 1 :]) / U[i, i]
    return xs

In [22]:
for i in reversed(range(5)):
    print(i)

4
3
2
1
0


In [23]:
help(np.triu)

Help on _ArrayFunctionDispatcher in module numpy:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of an array with the elements below the `k`-th diagonal
    zeroed. For arrays with ``ndim`` exceeding 2, `triu` will apply to the
    final two axes.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])
    
    >>> np.triu(np.arange(3*4*5).reshape(3, 4, 5))
    array([[[ 0,  1,  2,  3,  4],
            [ 0,  6,  7,  8,  9],
            [ 0,  0, 12, 13, 14],
            [ 0,  0,  0, 18, 19]],
           [[20, 21, 22, 23, 24],
            [ 0, 26, 27, 28, 29],
            [ 0,  0, 32, 33, 34],
            [ 0,  0,  0, 38, 39]],
           [[40, 41, 42, 43, 44],
            [ 0, 46, 47, 48, 49]

## Eliminación Gaussiana

In [24]:
def gauelim(inA, inbs):
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size

    for j in range(n - 1):
        for i in range(j + 1, n):
            coeff = A[i, j] / A[j, j]
            A[i, j:] -= coeff * A[j, j:]
            bs[i] -= coeff * bs[j]

    xs = backsub(A, bs)
    return xs

In [25]:
A = np.array([[1, 3, 8], [-2, np.pi, 0], [2, -1, 1]])

In [26]:
A

array([[ 1.        ,  3.        ,  8.        ],
       [-2.        ,  3.14159265,  0.        ],
       [ 2.        , -1.        ,  1.        ]])

In [27]:
b = np.array([1, 2, 3])

In [28]:
b

array([1, 2, 3])

In [29]:
x_solution = gauelim(A, b)

In [30]:
x_solution

array([ 3.6887277 ,  2.98493676, -1.45544225])

In [31]:
A @ x_solution

array([1.        , 2.        , 2.93707639])

In [32]:
b

array([1, 2, 3])

In [33]:
x_numpy_solution = la.solve(A, b)

In [34]:
x_numpy_solution

array([ 3.75167348,  3.02500929, -1.47833767])

## Descomposición LU

In [35]:
def ludec(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.identity(n)

    for j in range(n - 1):
        for i in range(j + 1, n):
            coeff = U[i, j] / U[j, j]
            U[i, j:] -= coeff * U[j, j:]
            L[i, j] = coeff

    return L, U

## Resolución de un sistema lineal vía LU

In [36]:
def lusolve(A, bs):
    L, U = ludec(A)
    ys = forsub(L, bs)
    xs = backsub(U, ys)
    return xs

In [37]:
x_lu = lusolve(A, b)

In [38]:
x_lu

array([ 3.75167348,  3.02500929, -1.47833767])

In [39]:
%time
y = [i for i in range(1000000)]

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 7.39 µs
