# Normas

In [1]:
import numpy as np
import numpy.linalg as la

In [11]:
x = np.random.randint(10, size=(5, 5))

In [12]:
x

array([[7, 8, 2, 7, 8],
       [3, 6, 5, 8, 9],
       [8, 4, 5, 3, 2],
       [3, 7, 4, 2, 9],
       [2, 5, 7, 9, 5]])

In [15]:
la.norm(x)

30.099833886584822

In [19]:
la.norm(x=x, ord=np.inf)

32.0

In [30]:
np.sum(a=x, axis=1)  # por filas

array([32, 31, 22, 25, 28])

In [28]:
np.sum(x[-1, :])  # Primera fila

28

In [31]:
la.norm(x=x, ord=-np.inf)

22.0

In [47]:
A = np.random.randint(10, size=(5, 5))
dA = np.random.random(size=(5, 5)) * 1e-2

In [48]:
A

array([[3, 3, 1, 2, 6],
       [8, 1, 8, 5, 9],
       [1, 9, 0, 7, 7],
       [9, 3, 0, 8, 5],
       [1, 4, 5, 4, 4]])

In [49]:
dA

array([[0.00533732, 0.00698019, 0.00984993, 0.00077721, 0.00865641],
       [0.00063524, 0.00260379, 0.00617104, 0.00080314, 0.00774337],
       [0.00028186, 0.0023061 , 0.00368198, 0.00443478, 0.00720759],
       [0.00589447, 0.00624625, 0.00610618, 0.00218517, 0.00882065],
       [0.00548409, 0.00539404, 0.00330818, 0.00436213, 0.00898157]])

In [50]:
A + dA

array([[3.00533732e+00, 3.00698019e+00, 1.00984993e+00, 2.00077721e+00,
        6.00865641e+00],
       [8.00063524e+00, 1.00260379e+00, 8.00617104e+00, 5.00080314e+00,
        9.00774337e+00],
       [1.00028186e+00, 9.00230610e+00, 3.68197812e-03, 7.00443478e+00,
        7.00720759e+00],
       [9.00589447e+00, 3.00624625e+00, 6.10617649e-03, 8.00218517e+00,
        5.00882065e+00],
       [1.00548409e+00, 4.00539404e+00, 5.00330818e+00, 4.00436213e+00,
        4.00898157e+00]])

In [55]:
b = np.random.randint(10, size=5)
db = np.random.random(size=5) * 1e-2

In [71]:
b = b.reshape(5, 1)

In [58]:
db

array([0.00179124, 0.00447149, 0.0010013 , 0.00929676, 0.00411637])

In [59]:
b + db

array([3.00179124, 3.00447149, 6.0010013 , 8.00929676, 3.00411637])

In [73]:
np.concatenate((A, b), axis=1 # matriz aumentada

array([[3, 3, 1, 2, 6, 3],
       [8, 1, 8, 5, 9, 3],
       [1, 9, 0, 7, 7, 6],
       [9, 3, 0, 8, 5, 8],
       [1, 4, 5, 4, 4, 3]])

In [65]:
A.shape

(5, 5)

In [72]:
b.shape

(5, 1)

In [74]:
b

array([[3],
       [3],
       [6],
       [8],
       [3]])

In [76]:
la.cond(A)

60.930772057178615

In [77]:
la.cond(A + dA)

60.21344278652582

$$
\frac{\|\Delta \mathbf{x}\|}{\|\mathbf{x}+\Delta \mathbf{x}\|} \leq\|\mathbf{A}\|\left\|\mathbf{A}^{-1}\right\| \frac{\|\Delta \mathbf{A}\|}{\|\mathbf{A}\|}
$$

In [79]:
la.norm(db) / la.norm(b + db)

0.00044789747999778414

In [80]:
la.norm(A) * la.norm(la.inv(A)) * la.norm(dA) / la.norm(A)

0.07290285213747842

In [81]:
M = np.zeros((8, 8))

In [84]:
M + 0.1

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]])

# La próxima sesión es el miércoles a las 6:00 pm